### ISSUE TITLE
BUG: Booking results not reflected

### ISSUE THREAD

**Issue by gnimnix** [rhdevs/rhapp#809] opened 2024-06-06 09:32 UTC
## Steps to reproduce:
1. Visit facility booking for dance studio.
2. Submit a booking in the new AY (tested for date 12 September 2024).

## Expected behaviour:
Bookings should be reflected but nothing is reflected.

## Tested on:
- macOS/iOS on chrome and firefox

**Comment by gnimnix** [comment] 2024-06-06 09:33
Update: problem seems to be on the frontend.

**Comment by kwangyy** [comment] 2024-07-31 09:27
As briefed a while back, this is not a bug, but a feature. Just for closure, I am closing this with this comment.

**Closed by kwangyy** 2024-07-31 09:27 UTC
Labels: bug, urgent
